name: deploy to lambda
on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: npm install and build
        run: |
          cd api && pnpm i
          pnpm run build
        env:
          CI: true

      - name: List Contents of root directory
        run: ls -la
          
      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        run: zip -qq -r dist.zip dist
        working-directory: api

      - name: List Contents of api directory
        run: ls -la api

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          # role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role

      - name: Check the functions
        run: |
          aws lambda update-function-code --function-name=beanstreet-func --zip-file=fileb://api/dist.zip
        
      # - name: default deploy
      #   uses: appleboy/lambda-action@v0.1.9
      #   with:
      #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws_region: ${{ secrets.AWS_REGION }}
      #     function_name: beanstreet-func
      #     # zip_file: api/dist.zip
      #     # memory_size: 128
      #     # timeout: 5
      #     # handler: handler
      #     # role: ${{ secrets.AWS_ROLE }}
      #     source: src/main.js
      #     # runtime: nodejs20.x
